[[majsoulrpa]]
remote_host = "127.0.0.1" # Optional. IP address of remote browser. If not specified, desktop mode will be used.
[majsoulrpa.authentication] # Optional (the following items are required if set).
email_address = "your_email_address@example.cfg" # Must be 50 characters or less.
[majsoulrpa.port] # Optional (all items below are also optional).
remote_port = 19222        # Port for browser remote control (default: 19222). Ignored in desktop mode.
proxy_port = 8080          # Browser proxy port (default: 8080).
message_queue_port = 37247 # Port of the message queue that stores Websocket messages (default: 37247).
[majsoulrpa.browser] # Optional (all items below are also optional). Ignored in remote mode.
# Support multiple monitors.
# The left edge of the primary monitor is 0 (default: 0).
# The top of the primary monitor is 0 (default: 0).
initial_position = { left = 100, top = 100 } # Either one can be set.
viewport_height = 720                        # Support from 720 to 2160 (default: 1080).
headless = false                             # Whether to run the browser headless (default: false).
user_data_dir = "./user_data"                # User data directory (comment out this line to use incognito mode).
